spring.datasource.url=jdbc:postgresql://localhost:5432/wsm_water_db
spring.datasource.username=postgres
spring.datasource.password=Pa$$w0rd

api.security.token.secret=${JWT_SECRET:my-secret-key}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
